apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-formation
  labels:
    app: gestion-formation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gestion-formation
  template:
    metadata:
      labels:
        app: gestion-formation
    spec:
      containers:
      - name: gestion-formation
        image: your-dockerhub-username/gestion-formation:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: root
