replicaCount: 1

image:
  repository: mysql
  tag: "5.7"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3306

ingress:
  enabled: false

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
